image: phaus/play2build:8

stages:
  - build
  - test
  - publish
  - deploy

sbt:
  stage: build
  tags:
    - docker
    - rack
  script:
    - sbt compile

test:
  stage: test
  tags:
    - docker
    - rack
  script:
    - sbt test

dist:
  stage: publish
  tags:
    - docker
    - rack
  script:  
    - sbt dist
  artifacts:
    paths:
    - target/universal/2fact-demo-*.zip

docker:
  stage: publish
  tags:
    - docker
    - create-container 
  script:  
    - sbt docker:publishLocal    

heroku:
  stage: deploy
  tags:
    - docker
    - rack
  script:
    - dpl --provider=heroku --app=a2fact-demo --api-key=$HEROKU_API_KEY
