image: phaus/play2build:8

stages:
  - build
  - test
  - publish
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

sbt:
  stage: build
  tags:
    - docker
    - rack
  script:
    - sbt compile -Dsbt.log.noformat=true -Dsbt.ivy.home=/cache/.ivy2/

test:
  stage: test
  tags:
    - docker
    - rack
  script:
    - sbt test -Dsbt.log.noformat=true -Dsbt.ivy.home=/cache/.ivy2/

dist:
  stage: publish
  tags:
    - docker
    - rack
  script:  
    - sbt dist -Dsbt.log.noformat=true -Dsbt.ivy.home=/cache/.ivy2/
  artifacts:
    paths:
    - target/universal/2fact-demo-*.zip

docker:
  stage: publish
  tags:
    - docker
    - rack
  script:
    - sbt docker:publishLocal -Dsbt.log.noformat=true -Dsbt.ivy.home=/cache/.ivy2/   
    - docker build -t $CONTAINER_TEST_IMAGE target/docker/stage
    - docker push $CONTAINER_TEST_IMAGE

heroku:
  stage: deploy
  tags:
    - docker
    - rack
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
    - git push -f heroku master
