image: phaus/play2build:8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - sbt compile

test:
  stage: test
  script:
    - sbt test

deploy:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    - dpl --provider=heroku --app=a2fact-demo --api-key=$HEROKU_API_KEY
