image: phaus/play2build:8

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - sbt compile

test:
  stage: test
  script:
    - sbt test

docker:
  stage: publish
  script:  
    - apt-get update -yq
    - apt-get install docker -y
    - docker info
    - sbt docker:publishLocal

deploy:
  stage: deploy
  script:
    - dpl --provider=heroku --app=a2fact-demo --api-key=$HEROKU_API_KEY
