image: phaus/play2build:8

stages:
  - build
  - test
  - publish
  - deploy

sbt:
  stage: build
  script:
    - sbt compile

test:
  stage: test
  script:
    - sbt test

dist:
  stage: publish
  script:  
    - sbt dist

docker:
  stage: publish
  script:
    - docker info    
    - sbt docker:publishLocal

heroku:
  stage: deploy
  script:
    - dpl --provider=heroku --app=a2fact-demo --api-key=$HEROKU_API_KEY
